ft(make homepage):Implementing home page and landing page
atlp-rwanda/tech-strikers-bn-frontend pull request #10
Opened 2021-02-02 20:25 UTC by Duncanwar

#### What does this PR do?
This PR implements the homepage and the landing page
#### Description of Task to be completed?
- I coded the UI by making small components.
- Making responsive design in react using bootstrap and react-strap
#### How should this be manually tested?
run: `https://github.com/atlp-rwanda/tech-strikers-bn-frontend.git`
-`git checkout ft-homepage`
-`npm install`
-`npm run dev`
type in browser URL tab `localhost:7000/dashboard`
#### Any background context you want to provide?
If your feature depends on homepage you can rebase this one and use it
#### What are the relevant pivotal tracker stories?
No PT story
#### Screenshots (if appropriate)
![Screenshot from 2021-02-02 22-06-36](https://user-images.githubusercontent.com/57761095/106658045-757bf800-65a5-11eb-90e9-8dec43cbdfe8.png)
![Screenshot from 2021-02-02 22-24-56](https://user-images.githubusercontent.com/57761095/106658089-8167ba00-65a5-11eb-8067-59e7c29f9efe.png)

#### Questions:

2021-02-03 01:48 UTC, BiGelio commented
This looks good but it will be much better if you try to use proper name(title) for this PR!

2021-02-05 11:51 UTC, hervebu requested changes
This branch is some commits behind develop!

2021-02-05 14:37 UTC, hervebu approved these changes

2021-02-05 17:28 UTC, BiGelio approved these changes

2021-02-11 12:20 UTC, merged