chore(route):react router dom
atlp-rwanda/tech-strikers-bn-frontend pull request #7
Opened 2021-01-29 09:41 UTC by tytyne

#### What does this PR do?
- create routers
#### Description of Task to be completed?
- create components
- create routers
#### How should this be manually tested?
- run` git clone  git clone https://github.com/atlp-rwanda/tech-strikers-bn-frontend.git`
- run `cd tech-strikers-bn-frontend `
- run `git checkout ch-react-router-175636782 `
- run `npm run dev`
#### Any background context you want to provide?
no
#### What are the relevant pivotal tracker stories?
[#175636782 ](https://www.pivotaltracker.com/story/show/175636782)
#### Screenshots (if appropriate)
#### Questions:

2021-02-02 11:43 UTC, hervebu requested changes

2021-02-02 11:43 UTC, hervebu commented on src/index.js
> +// ReactDOM.render(routing, document.getElementById('root'));
Would you please uncomment these lines of codes if they are unnecessary

2021-02-02 11:43 UTC, hervebu commented on src/index.js
> +// ReactDOM.render(routing, document.getElementById('root'));
Would you please uncomment these lines if possible.

2021-02-03 08:13 UTC, BiGelio approved these changes

2021-02-03 08:52 UTC, closed without merging